### PR TITLE
semantic import

### PR DESCRIPTION
**Pull request by ErikWil**
- Import of semantic modules to Hive
- case insensitive item attribute/module property access
- Possibility to set several attributes on item creation. Attributes can be passed as dict or **keywords
- Possibility to set several properties on module creation. Properties can be passed as dict or **keywords
- Added internal function _normalize_input to handle dict attributes and **kw arguments.

### CODE REVIEW

**Comment by alydersen** [comment]
Suggested method for _normalize_input also. What do you think?

**Comment by ErikWil** [comment]
Yes. Added to the description now

**Review by alydersen — APPROVED** [review]

**Comment by PetterBMarkussen** [comment]
Hei, 

Can we merge this branch into main, as the normalization is implemented?

**Comment by alydersen** [comment]
@ErikWil @PetterBMarkussen Merged and deleted the branch

**Pull request merged**
